### ISSUE TITLE
Broken link of "example project" in docs

### ISSUE THREAD

**Issue by NicolaeNMV** [com-lihaoyi/cask#117]
Hi,

First of all I want to thank the author of this project for the amazing work.

So I wanted to try out the cask library, I went to the documentation page https://com-lihaoyi.github.io/cask/

But it appears that the [download link](https://github.com/com-lihaoyi/cask/releases/download/a70801b401109a52b44c43d0c4a9857afd47e8e2/minimalApplication-a70801b401109a52b44c43d0c4a9857afd47e8e2.zip) is broken. I'm getting a "Not Found" github page.
I see that the code that does the pre-processing is in [docs/build.sc](https://github.com/com-lihaoyi/cask/blob/master/docs/build.sc#L35).

I would like to contribute a bit more, if that's okay. Mainly on docs.

1. It would be nice to create a separate github project that anyone can run `git clone`. I believe that everyone has git installed, and there is more trust when getting something directly off git. I see that is a widely popular method of onboarding ([spring boot](https://spring.io/guides/gs/spring-boot/), [akka-http](https://doc.akka.io/docs/akka-http/current/introduction.html), [play](https://www.playframework.com/getting-started)).
2. Provide the dependencies in the format of multiple build tools that can be copied. I feel like allowing the use of the widely popular build tools is a good idea for onboarding: maven, sbt, mill. A bit like [akka-http](https://doc.akka.io/docs/akka-http/current/introduction.html) did it for sbt and maven.
After all, I don't think anyone will change their build tool just for one project. There is a bigger game ; ) I think the simple style of Scala is very appealing!
3. The cask server doesn't print the port when it starts.
4. There is a link to gitter from the docs, I think now the community is on discord. I will raise a PR for this one.

**Comment by lihaoyi** [comment]
Fixed in https://github.com/com-lihaoyi/cask/commit/b51c072a3b55afbd8798d51bf589a9212401e228

Thanks for the report!
