### ISSUE TITLE
Error parsing BigDecimal path arguments

### ISSUE THREAD

**Issue by aaronp** [com-lihaoyi/cask#120]
Consider the following route:
```
  @cask.get("/echo/:x")
  def echo(x: BigDecimal) = x.toString
```

the route macro will fail with the following error on initialization:
```
[error] 47 |  initialize()
[error]    |  ^^^^^^^^^^^^
[error]    |  no reader of type scala.math.BigDecimal found for parameter x
```

It seems BigDecimal should be supported by default, and the documentation would benefit from clear instructions on how to add new path parsers for different types.

(And my apologies if I've just been to thick to find it! Thanks so much for the fantastic platform)

**Comment by lihaoyi** [comment]
I think you need to define an implicit `ParamReader` for `BigDecimal` https://github.com/com-lihaoyi/cask/blob/1b13abceb474be306b33c2aa197b583602b26be1/cask/src/cask/endpoints/ParamReader.scala#L8-L11

**Comment by aaronp** [comment]
Thanks so much Li - closing this issue
