### ISSUE TITLE
Any thoughts for Cloudflare Workers?

### ISSUE THREAD

**Issue by windymelt** [com-lihaoyi/cask#131]
[Cloudflare Workers](https://developers.cloudflare.com/workers/) is small but nice platform to build cloud API: if we export default function, [Cloudflare automatically execute it on each request](https://developers.cloudflare.com/workers/examples/return-html/).

As we know, Cask is also small but nice platform to build API in Scala. It goes along simple Scala manner, easy to use.

My idea is: Providing Cloudflare Worker module in Cask makes great synergy in Scala ecosystem. If we turn Cask code into one function that recognize request and return result, we can run Cask in Cloudflare ecosystem immidiately (Just like [Hono](https://hono.dev). We can compete against it).

Could you tell me your opinion about bridging Cask and CF Workers?

**Comment by lihaoyi** [comment]
Cask doesn't run on Javascript, so it seems like it won't work
