### ISSUE TITLE
Feature request: Support OPTIONS requests?

### ISSUE THREAD

**Issue by exue** [com-lihaoyi/cask#16]
I noticed GET, PUT, POST, and WebSocket requests are supported so far, any plans on supporting OPTIONS?

https://github.com/lihaoyi/cask/blob/7476d7a08c2f62d4dc03cfb4f8f4a30060cafdb7/cask/src/cask/main/Main.scala#L128

**Comment by jodersky** [comment]
Allowing arbitrary http methods is being implemented in #27. This should allow you to handle option requests manually.

**Comment by lihaoyi** [comment]
I guess we can call this done
