### ISSUE TITLE
Documentation not updated when new versions are published

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [com-lihaoyi/cask#25]
Latest version is 0.5.6, but the [documentation](http://www.lihaoyi.com/cask/index.html) references 0.5.2:

```
Cask is just a Scala library, and you can use Cask in any existing Scala project via the following coordinates:

// Mill
ivy"com.lihaoyi::cask:0.5.2"

// SBT
"com.lihaoyi" %% "cask" % "0.5.2"
```
It would be interesting to mention that Scala 2.13 is required.

**Comment by jodersky** [comment]
Agreed, it would be nice to mention that! The docs are included in the repo btw, https://github.com/lihaoyi/cask/blob/master/docs/pages/1%20-%20Cask:%20a%20Scala%20HTTP%20micro-framework.md so a PR would be welcome I reckon
