### ISSUE TITLE
example project returns "/" as document not HTML

### ISSUE THREAD

**Issue by yatesco** [com-lihaoyi/cask#53]
Hi - I downloaded the example "TodoMVC Full Stack Web" example project following the link (https://github.com/lihaoyi/cask/releases/download/0.7.8/todo-0.7.8.zip) from https://com-lihaoyi.github.io/cask/#todomvc-api-server and then ran `./mill app.run`.

Visiting `http://localhost:8080` gives:

<img width="542" alt="image" src="https://user-images.githubusercontent.com/181469/124924365-4b66b000-dff3-11eb-93b4-cb35a0948ffe.png">

<img width="729" alt="image" src="https://user-images.githubusercontent.com/181469/124924390-50c3fa80-dff3-11eb-9f47-3c6d1eb13127.png">

I'm just reading the docs so I don't really know how to fix it, hence no PR.

Thanks!

**Comment by Quafadas** [comment]
It's not super well documented. This sets the mime type for javascript. Am guessing you'd need to set mime type for the html 

https://github.com/OpenResult/caskscalajs/blob/master/server/src/Server.scala

**Comment by mjhopkins** [comment]
@Quafadas That's only relevant for static files.
The issue seems to be that `TypedTag` is supposed to set the content type

```scala
override def httpContentType = Some("text/html")
```

but this doesn't work and instead you always get `text/plain`.

**Comment by lihaoyi** [comment]
Should be fixed by https://github.com/com-lihaoyi/cask/commit/c9ee4bb0da6fa25bf2e27955534da94b3bee170c

**Comment by yatesco** [comment]
thanks @lihaoyi
