### ISSUE TITLE
Suppress match may not be exhaustive compiler warning

### ISSUE THREAD

**Issue by pathikrit** [com-lihaoyi/cask#62]
I am on Scala 2.13 and I like to enable compiler warnings on non-exhaustive pattern matching but when I enable it, the following piece of code:

```scala
@cask.get(s"/app/:app")
  def routeApp(app: String) =
    s"Hello $app!"

@cask.staticFiles("/js/")
  def scalaJs() =
    "web/target/scala-2.13/web-fastopt/"
```

spits these warnings:
```
[info] compiling 1 Scala source to target/scala-2.13/classes ...
[error] Router.scala:25:7: match may not be exhaustive.
[error]   def routeApi(req: cask.Request) =
[error]       ^
[error] Router.scala:16:7: match may not be exhaustive.
[error] It would fail on the following input: (x: Seq[?] forSome x not in Nil)
[error]   def scalaJs() =
[error]       ^
```

I cannot myself add `@unchecked` anywhere because the code is being generated by macro expansion. So perhaps in the macro expansion itself, can we add the `@unchecked` annotation?

**Comment by lihaoyi** [comment]
As a workaround, you should be able to annotate the `initialize()` call with `@nowarn` to shut it up i think

**Comment by pathikrit** [comment]
Ah yes that worked (putting `@nowarn` on the object which has `initialize()` in it)

**Comment by lihaoyi** [comment]
@pathikrit does `initialize(): @nowarn` work? that would let you cut down the scope of the nowarn to only where it's needed

**Comment by pathikrit** [comment]
No I tried:

```scala
  initialize(): @nowarn
```
and I got:
```
[error] Router.scala:29:18: @nowarn annotation does not suppress any warnings
[error]   initialize(): @nowarn
[error]                  ^

```

Then I tried:
```scala
  @nowarn
  initialize()
```
The above fails to compile:
```
[error] Router.scala:30:3: expected start of definition
[error]   initialize()
[error]   ^
```

```
