### ISSUE TITLE
Type safe decorators?

### ISSUE THREAD

**Issue by yatesco** [com-lihaoyi/cask#63]
Hi there - thanks for this!

I notice that the decorators populate downstream with string based keys:
```scala
  class withExtra extends cask.RawDecorator {
    def wrapFunction(ctx: cask.Request, delegate: Delegate) = {
      delegate(Map("extra" -> 31337))
    }
  }

  @withExtra()
  @cask.get("/hello/:world")
  def hello(world: String)(extra: Int) = {
    world + extra
  }
```

Is there a way/a plan to make these type safe (enums for example)? My concern is that renaming the parameter name won't pick up the string key in the decorator's output, but this won't be picked up until runtime.

Thanks!

**Comment by jodersky** [comment]
There are no plans for this AFAIK. I don't know how to do it, but if you wanted to try it you would need to:

a) change the `Delegate` to not use `Map`s but something more type safe (in Scala 3, literal types may help ;))
b) change the macros to handle a)
