### ISSUE TITLE
Documentation speaks about `cask.Subpath`

### ISSUE THREAD

**Issue by OndrejSpanel** [com-lihaoyi/cask#95]
Documentation in https://com-lihaoyi.github.io/cask/#variable-routes says:

> you can set the flag subpath=true and ask for a : cask.Subpath

However no `cask.Subpath` seems to exist, even the sample in the documentation uses `request: cask.Request`.

**Comment by lihaoyi** [comment]
I think the docs are out of date, `cask.Subpath` was removed in https://github.com/com-lihaoyi/cask/commit/4b0cfdf0eeca46cfccbf9fe42af42f383932c427 it seems the current way is to ask for `request.remainingPathSegments`

**Comment by lihaoyi** [comment]
Updated the docs in https://github.com/com-lihaoyi/cask/commit/7bd5f2da5423ee95f7591cbfaa2d650396cddfc5
