### ISSUE TITLE
Document optional query parameters

### ISSUE THREAD

**Issue by OndrejSpanel** [com-lihaoyi/cask#98]
This took me a while to find:

```scala
  @cask.get("/get")
  def hello(param: String = "Default") = {
    s"Hello $param"
  }
```

or:

```scala
  @cask.get("/get")
  def hello(param: Option[String] = None) = {
    s"Hello $param"
  }
```

This way the query parameter is optional. It may seem intuitive, but I have tried several different ways before trying this (e.g. just making param: Option[String]. or providing overloads of def hello).

**Comment by lihaoyi** [comment]
This is covered in the section on [Variable Routes](https://com-lihaoyi.github.io/cask/index.html#variable-routes) I think

> You can bind variables to endpoints by declaring them as parameters: these are either taken from a path-segment matcher of the same name (e.g. `postId` above), or from query-parameters of the same name (e.g. `param` above). You can make param take a `: String` to match `?param=hello`, an `: Int` for `?param=123` a `Seq[T]` (as above) for repeated params such as `?param=hello&param=world`, or `: Option[T]` for cases where the `?param=hello` is optional.

**Comment by lihaoyi** [comment]
Added more docs in https://github.com/com-lihaoyi/cask/pull/107
